### ISSUE TITLE
Allow configuration folder to be mounted from host

### ISSUE THREAD

**Issue by pengux** [Painted-Fox/docker-postgresql#6]
Currently there is no way to change postgresql configuration without rebuilding the image. A suggestion is to mount a folder from host to be used as configuration folder for postgresql in the container.

**Comment by jonmorehouse** [comment]
Solid idea, though I honestly think its overkill for this image. I think configuration via environment hosts is easiest and I don't really think rebuilding the image is a huge issue for now. I'm working on #4 so maybe some of the settings there will make this feature more relevant

**Comment by Painted-Fox** [comment]
This should now be addressed.
